### ISSUE TITLE
Add an example implementation of `vkGetValue` 

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Guide#10]
In the "pNext and sType" chapter, so that it is clear how it uses `pNext` and `sType` to set the value for `b` as well as for `a`.

For example (not sure if this is correct):
```
{
    a.value = 0;
    if (a.pNext != nullptr) {
        auto b = reinterpret_cast<VkB *>(a.pNext);
        if (b->sType == VK_STRUCTURE_TYPE_B) {
              b->value = 0;
        }
    }
}
```

**Comment by sfricke-samsung** [comment]
I thought about this recently too, it would be nice to add a second part explaining that/giving example. I'm happy to write up something first for a review or you can
