### ISSUE TITLE
Adding chapter on HLSL shader model coverage

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Guide#122]
As the question comes up here and there, would it make sense to have chapter on Vulkan's coverage of the different HLSL shader models?

Similar to this slide [from this presentation](https://www.khronos.org/assets/uploads/developers/library/2018-siggraph/05b-Vulkan-Shader-Compiler-Updates_Aug18.pdf):

![image](https://user-images.githubusercontent.com/10283127/124966836-09099700-e024-11eb-9105-332479b75eb5.png)

E.g. for [SM 6.6](https://devblogs.microsoft.com/directx/in-the-works-hlsl-shader-model-6-6/) afaik at least some features are already present in Vulkan via certain extensions.

**Comment by sfricke-samsung** [comment]
So I 100% agree there should be an HLSL chapter, I have zero knowledge about HLSL, so I never felt confident writing up... would be grateful if you wanted to start a chapter, don't need much, but as you said, would be at least a place holder for future things if people want to add

**Comment by SaschaWillems** [comment]
I'm not too knowledgeable with HLSL too, but I could do a basic chapter on how HLSL fits into Vulkan and a table that maps shader model versions to Vulkan features. I'll try to whip up something and do a PR.
