### ISSUE TITLE
How about add another link of helpful post of synchronization?

### ISSUE THREAD

**Issue by sein519** [KhronosGroup/Vulkan-Guide#137]
Hi, I'm recently studying about synchronization(legacy) and thanks for this repo, got tons of knowledge from the synchronization post. It provides us several of useful references but I got some understanding from [this post](https://www.khronos.org/blog/understanding-vulkan-synchronization) as well. So why don't you add that post? I think it can give meaningful intuitives to beginners.

**Comment by sfricke-samsung** [comment]
Sorry, I realize I never got around to adding the link to that blog. Thanks for pointing that out
