### ISSUE TITLE
No samples containing main()

### ISSUE THREAD

**Issue by awsdert** [KhronosGroup/Vulkan-Guide#14]
I'm trying learn via the web  but every "sample" I look at makes no mention of main() and how to go about getting a thread of vulkan, specifically I want to offload some code to my gfx card to cut down the time it takes to stress test it, I basically wrote a function under MIT License to read a float string and output a float or double or long double or any other size based on what the user provides, it worked fine in when I did upto 128.128e+/-128 but my CPU is not cut out for checking every number between 0.0e+-/0 to 1024.1024e+/-1024, that's over a billion numbers to try while also using slower big int routines to cope with flexible size.

**Comment by sfricke-samsung** [comment]
So `main()` is usually a C/C++ entry point function to where the process of a program starts. Vulkan runs along with all the other stuff you have in a normal C/C++ program.

The `vkCreateInstance()` is the equivalent "main" you are referring to. This call will create a Vulkan context as a `VkInstance` handle. With this you can create a `VkDevice` from `VkCreateDevice()`. From there, along with a lot more stuff I am hand waving here, you essentially create a `VkCommandBuffer` of work that is submitted to the `VkDevice` in a `VkQueue`. So when you call `VkQueueSumit()` the CPU will offload work to run on the GPU

**Comment by awsdert** [comment]
Thank you, I'll try when I get time
