### ISSUE TITLE
Typo in sentence

### ISSUE THREAD

**Issue by ikapoura** [KhronosGroup/Vulkan-Guide#153]
Hello there.

I think that "T) which is only designed for emulation layers" at the end of [https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/validation_overview.adoc](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/validation_overview.adoc) is a mistake. I don't know what would be the correct version to open a corrective PR.

**Comment by sfricke-samsung** [comment]
seems to have been clobbered when converted to asciidoc

https://github.com/KhronosGroup/Vulkan-Guide/commit/21a67a93f90eca38dbb621ecf642d6a15e5f1922#diff-085ba6c08579af1be499c9a1321db0a0d6d02b5631cfb270bcfde51c2f6509ed

will fix, thanks for pointing that out!
