### ISSUE TITLE
Add section about different ways of uploading data to the GPU?

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Guide#156]
During a recent Vulkan documentation related call, we've been talking about having a single resource on the different ways for getting data uploaded to the GPU. E.g. using uniform buffers, storage buffers, push constants (for which there is already a PR), etc.

We were wondering if this would be a good fit for the Vulkan guide? It doesn't have to be too detailed, but more of a "hey, here are all the ways of getting data to the GPU and here are some things you need to consider when using this and that way".

**Comment by sfricke-samsung** [comment]
I think between 

https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/mapping_data_to_shaders.adoc
and
https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/vertex_input_data_processing.adoc

a lot of this is covered.

Was there a specific example that originally sparked this idea?

**Comment by SaschaWillems** [comment]
No specific sample. This came up on a tutorial related call and we were trying to decide where such information would make most sense. 

The two chapters you posted look mostly like what we were imagining, so we may just link to them :)
