### ISSUE TITLE
Asciidoctor error on Make - MacOS

### ISSUE THREAD

**Issue by ThePseudo** [KhronosGroup/Vulkan-Guide#157]
Using MacOS and compiling the guide the following error shows up:
```
asciidoctor --failure-level WARNING -b html5 guide.adoc
asciidoctor: WARNING: chapters/extensions/VK_KHR_sampler_ycbcr_conversion.adoc: line 19: id assigned to section already in use: formats
make: *** [guide.html] Error 1
```
However, the guide.html file is generated. Is it ok?

**Comment by sfricke-samsung** [comment]
First, sorry for the long delay (holidays)

second, this isn't a MacOS issue, I see it as well... I need to add a small CI to make sure building the full single page guide doesn't break or throw warning... Thanks for bringing this up, I will get a fix up soon and CI added hopefully not too long after

**Comment by ThePseudo** [comment]
Thank you! And don't worry, it was holiday time for everyone! 😅
