### ISSUE TITLE
Add CI to check or build single page guide

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-Guide#159]
as stated in #157 it would be nice to either

1. Add CI to check no warnings are generated when building the guide
2. host the guide.html file somewhere automatically when the guide is updated

**Comment by oddhack** [comment]
Since we're moving towards publishing through Antora in a couple of months, we may want to close this as WONTFIX rather than publish a new artifact. N.b. it seems unfortunate that the top search results for "Vulkan Guide" do not point to a Khronos website.

**Comment by spencer-lunarg** [comment]
Closing as noted above
