### ISSUE TITLE
vkFreeMemory() memory leaks while the VkDeviceMemory object was allocated with VkExportMemoryAllocateInfo

### ISSUE THREAD

**Issue by lxrui** [KhronosGroup/Vulkan-Guide#197]
I am using the VK_KHR_external_memory_win32 extension to share GPU memory with OpenGL on Windows, the shared texture works fine.
The memory was allocated by vkAllocateMemory() with VkMemoryAllocateInfo that the pNext contains a VkExternalMemoryImageCreateInfo structure whose handleTypes is VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT/VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV, but the memory will not return to GPU memory heap after the related VkDeviceMemory object was freed by vkFreeMemory().
I have test Intel HD 630 / AMD RX 5700XT / Nvidia 1660 Ti graphics cards, all of them have the memory leaks issue no matter if the dedicated memory is enable or not.

**Comment by sjfricke** [comment]
Hello @lxrui 

First, the Vulkan Guide is not a dedicated place to ask for debugging help, my advice would to ask your questions in one of the community platforms instead
https://vulkan.org/#join-our-community

**Comment by lxrui** [comment]
Thanks @sjfricke 
I post this issue on [stackoverflow](https://stackoverflow.com/questions/73711305/vkfreememory-memory-leaks-while-the-vkdevicememory-object-was-allocated-with-vke)

**Comment by marty-johnson59** [comment]
Is there anything else to do on this one, or shall we close it out?  Thx
