### ISSUE TITLE
compare directX11 and vulkan in UE5 use NVIDIA Nsight

### ISSUE THREAD

**Issue by Judgecut** [KhronosGroup/Vulkan-Guide#204]
ue5 render VolumetricCloud call vkCmdDispatch use 0.88ms  capture frame in Nsight.
![image](https://user-images.githubusercontent.com/58514140/204480638-051cd95d-f32b-4283-b0ff-c689fd4f9ed3.png)
but use directX11 call Dispatch use 0.40ms only.
![image](https://user-images.githubusercontent.com/58514140/204480819-1a584f4c-ab89-441f-91f3-98188d0e17f4.png)
it is a little strange.
figure of vulkan API call:
![image](https://user-images.githubusercontent.com/58514140/204481584-4db10032-52f3-40e7-b13f-b3ad5246f90d.png)
figure of dx11 API call:
![image](https://user-images.githubusercontent.com/58514140/204481711-8186cfdf-2d7c-44cd-9ab5-d86b8e0978c6.png)

**Comment by Judgecut** [comment]
I don't know it is normal

**Comment by spencer-lunarg** [comment]
@Judgecut sorry this repo is for giving guide information about Vulkan as an API, this seems to be an issue with the driver's implementation of Vulkan. Also note that Dx11 (similar to OpenGL) is different way of controlling the GPU and might put more work at the `Draw` command vs earlier commands.

There are many Vulkan community that are welcoming to discuss this issue https://www.vulkan.org/#join-our-community

Closing as this is not the correct spot to report this, sorry

**Comment by Judgecut** [comment]
ok thanks
