### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Guide#205]
This repo slipped under the radar somehow but should do this to abide by Khronos policy. Not sure who admins the repo but I'm happy to do it if you want - as with all the other repos, it's just a matter of invoking the github renaming tool.

**Comment by spencer-lunarg** [comment]
> Not sure who admins the repo but I'm happy to do it if you want

I have no experience doing it, so if you want to do it that would probably be better

**Comment by oddhack** [comment]
> > Not sure who admins the repo but I'm happy to do it if you want
> 
> I have no experience doing it, so if you want to do it that would probably be better

Go to Settings / Code & Automation / Branches and edit the default branch, is all.

Happy to do it but we should have a heads-up - I will mention it on the Maintenance call tomorrow. There is minimal impact as Github sets up some forwarding as part of the renaming tool, but best for people with local repo clones to pull the new main branch and switch to using that.

**Comment by marty-johnson59** [comment]
@gpx1000 and I typically review Guide issues on the Vulkan samples call (next on on Monday). This looks straight forward enough, but let's review there for visibility.

**Comment by oddhack** [comment]
> @gpx1000 and I typically review Guide issues on the Vulkan samples call (next on on Monday). This looks straight forward enough, but let's review there for visibility.

@marty-johnson59 Did you get a chance to review this yet?

**Comment by marty-johnson59** [comment]
Not yet - Steve was OOO on our last call.  @gpx1000, can you take a look and if OK, I'll merge.  Thx

**Comment by gpx1000** [comment]
It LGTM.  Go ahead and merge please Marty.  Sorry I've been so reclusive, am getting closer to back to normal.

**Comment by marty-johnson59** [comment]
Great to hear!

OK, I edited the default branch to "main" - hoping that doesn't break anything.  LMK if there's more to be done here.  Thx!

**Comment by oddhack** [comment]
> Great to hear!
> 
> OK, I edited the default branch to "main" - hoping that doesn't break anything. LMK if there's more to be done here. Thx!

Thanks, LGTM. You may also want to edit the branch protection settings (same settings page as the default branch) to protect 'main' so only repo admins can push commits to it, otherwise nothing more TBD. Feel free to close whenever you like.

**Comment by oddhack** [comment]
> Done. BTW, I suppose we should make the same change (to "main") on the Samples repo? That's still set to "master"

Yes, that would be great. Thanks!

**Comment by marty-johnson59** [comment]
Done, closing
