### ISSUE TITLE
Add chapter with GLSL to HLSL mapping

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Guide#218]
We already have a decoder ring with terminologies compared across different apis. I think it would be good idea to have something similar for GLSL and HLSL. I often find it difficult to find HLSL terms matching GLSL terms, e.g. built-ins. 

The list from [here](https://anteru.net/blog/2016/mapping-between-HLSL-and-GLSL/) is something we could use as a base and then add in newer mappings, e.g. for ray tracing, mesh shading etc.

[This document](https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/SPIR-V.rst) could also be used for sourcing information.

**Comment by spencer-lunarg** [comment]
100% agree, this would be a very useful addition!

**Comment by SaschaWillems** [comment]
Awesome. I'll try to get something up and running based on above links. Learned a lot while porting the GLSL shaders for my samples to HLSL that should prove helpful for this :)

**Comment by SaschaWillems** [comment]
Here is a first very work-in-progress version of what I have in mind: https://github.com/SaschaWillems/Vulkan-Guide/blob/shader_language_mapping/chapters/high_level_shader_language_comparison.adoc

It's still lacking (probably a lot) stuff and needs restructuring. But I can imagine that it would be useful to esp. those that know GLSL and want to move to HLSL.

**Comment by spencer-lunarg** [comment]
This is awesome! I agree could probably use some small cleanup and restructuring and more stuff added, but just having this nicely together showing the difference is such an useful addition to the ecosystem

**Comment by SaschaWillems** [comment]
Fixed via #244
