### ISSUE TITLE
Missing links in layers documentation

### ISSUE THREAD

**Issue by jeroenbakker-atmind** [KhronosGroup/Vulkan-Guide#252]
https://docs.vulkan.org/guide/latest/layers.html#_creating_a_layer has links to github resources about the layer factory tool. These links are outdated. 

I didn't find any references to layer factory in this repository, so I might be in the wrong place. Please close this issue when so and refer me to the right location.

**Comment by oddhack** [comment]
Moved to Vulkan-Guide. A risk of combining documentation from several different repos into one site, but it's good to see people using it.
