### ISSUE TITLE
Incorrect sparse texture status HLSL mapping 

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/Vulkan-Guide#255]
https://github.com/KhronosGroup/Vulkan-Guide/blob/c432ecbfc7439788ff0d7b75c99a34446c2c7897/chapters/high_level_shader_language_comparison.adoc#L580

`sparseTexelsResidentARB` corresponds to HLSL's `CheckAccessFullyMapped`.

**Comment by SaschaWillems** [comment]
Thank you very much for your feedback. Would be nice if you could put all the feedback related to that new page into one single issue. That makes it a lot easier for me to track.
