### ISSUE TITLE
Vulkan injection issue

### ISSUE THREAD

**Issue by elpie89** [KhronosGroup/Vulkan-Guide#74]
Hi, I'm working on a Vulkan application (that has nothing to do with OBS).. and I have strange messages and unexpected crash

```
[OBS] OBS_CreateDevice: texture sharing is not supported
[OBS] Failed to open pipe
[OBS] graphics-hook.dll loaded against process: coffeecupd.exe
[OBS] (half life scientist) everything.. seems to be in order
```
Seems like obs is injecting something in my code..how can I isolate my Vulkan application?

**Comment by sfricke-samsung** [comment]
@elpie89 

So some advice would be to

1. Set `VK_LOADER_DEBUG=all` to have the Vulkan Loader print out information. While slightly verbose, this will have the information about which driver is loaded, which layer is loaded, etc. The Vulkan Loader is called at `vkCreateInstance` so it will be the first thing you see

2. My other advice is to set the [api dump layer](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) which will print out each time a Vulkan API call is made. This will at least let you determine "when" the Vulkan application is occurring

Hope this helps, but closing as this seems like an OBS issue more than the Vulkan-Guide issue
