### ISSUE TITLE
Add chapter around how memory is laid out for descriptor binding

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-Guide#76]
Similar to to the [Vertex Input Data](https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/vertex_input_data_processing.md) chapter, but around the use of buffer memory blocks in relation to each of the parameters in DescriptorBufferInfo, DescriptorSetLayoutBinding, WriteDescriptorSet and vkCmdBindDescriptorSets

**Comment by axsaucedo** [comment]
+1 - this would be really useful

**Comment by sfricke-samsung** [comment]
closed from https://github.com/KhronosGroup/Vulkan-Guide/pull/161
