### ISSUE TITLE
Add a link to Vulkan Samples

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Guide#8]
Not sure which chapter would be most relevant, maybe we could add it in the README?

Thank you!

**Comment by sfricke-samsung** [comment]
I would argue the main README should remain a pure table of content page

I would add a section/blurb in the development_tools.md chapter

**Comment by JoseEmilio-ARM** [comment]
Done in https://github.com/KhronosGroup/Vulkan-Guide/pull/7

**Comment by sfricke-samsung** [comment]
Fixed in #7
