### ISSUE TITLE
Add a section on `LAZILY_ALLOCATED_BIT`

### ISSUE THREAD

**Issue by JoseEmilio-ARM** [KhronosGroup/Vulkan-Guide#9]
In the "Memory Allocation Strategy" chapter. 

This is important for tiled (most mobile) GPUs since they can optimize an attachment that will only be used in a single render pass and doesn't need to be stored

We could also link to the [spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#memory-device-lazy_allocation) and Khronos' [tutorial](https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/performance/render_subpasses/render_subpasses_tutorial.md#Transient-Attachments) for more info.

Thank you!

**Comment by sfricke-samsung** [comment]
Sure feel free to write up a small section and attach to your current PR

**Comment by JoseEmilio-ARM** [comment]
Done

**Comment by sfricke-samsung** [comment]
fixed in #7
